version: '3'
services:
  app:
    container_name: avaliacao-gsw
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongoAvaliacao
    image: mongo
    ports:
      - '27017:27017'